# Generated by Django 3.0.8 on 2020-07-28 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinkBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='link',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
